// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmlqDPD10uTVKjAmswY56VbCv8TQssdGQ',
    appId: '1:579330838896:web:a46845a88df6be919a3fb5',
    messagingSenderId: '579330838896',
    projectId: 'notifications-3d16e',
    authDomain: 'notifications-3d16e.firebaseapp.com',
    databaseURL: 'https://notifications-3d16e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'notifications-3d16e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2NiPOCZlNzL3TXldiYhTpnL-H34EDoGQ',
    appId: '1:579330838896:android:03bf83cea26acc419a3fb5',
    messagingSenderId: '579330838896',
    projectId: 'notifications-3d16e',
    databaseURL: 'https://notifications-3d16e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'notifications-3d16e.firebasestorage.app',
  );
}
